# Generated by Django 4.0.4 on 2022-08-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api', '0002_view_role_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='socket_session_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
