# Generated by Django 4.0.4 on 2022-07-31 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('residence_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='direction_from',
        ),
        migrations.RemoveField(
            model_name='order',
            name='direction_to',
        ),
        migrations.AddField(
            model_name='order',
            name='address_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderfrom', to='orders.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='address_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderto', to='orders.address'),
            preserve_default=False,
        ),
    ]
